<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>Decompile.re Setup Wizard</AssemblyName>
    <RootNamespace>DecompileRe.SetupWizard</RootNamespace>
    <RuntimeIdentifiers>win-x64;win-arm64;osx-x64;osx-arm64;linux-x64;linux-arm64</RuntimeIdentifiers>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <ProjectReference Include="..\DecompileRe.SetupWizard.Core\DecompileRe.SetupWizard.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
    <EmbeddedResource Include="Assets\release-signing-public-key.pem"
                      LogicalName="DecompileRe.SetupWizard.release-signing-public-key.pem" />
  </ItemGroup>
</Project>
